<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Music Ocean</title>
    <!-- One style sheet generated by Laravel -->
    <link href="/css/app.css" rel="stylesheet">
  </head>
  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          @include('inc.navbar')

          @include('inc.section')

          @include('inc.footer')
        </div>
      </div>
    </div>
  </body>
</html>
